# Generated by Django 5.2.4 on 2025-07-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('center_station', models.CharField(max_length=50)),
                ('status', models.CharField(default='waiting', max_length=20)),
                ('team_a_score', models.IntegerField(default=0)),
                ('team_b_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
